// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Coupon is the predicate function for entcoupon builders.
type Coupon func(*sql.Selector)

// Currency is the predicate function for currency builders.
type Currency func(*sql.Selector)

// Milestone is the predicate function for milestone builders.
type Milestone func(*sql.Selector)

// Progress is the predicate function for progress builders.
type Progress func(*sql.Selector)

// Reward is the predicate function for reward builders.
type Reward func(*sql.Selector)
