// Code generated by ent, DO NOT EDIT.

package milestone

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the milestone type in the database.
	Label = "milestone"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStoreID holds the string denoting the store_id field in the database.
	FieldStoreID = "store_id"
	// FieldExpireAt holds the string denoting the expire_at field in the database.
	FieldExpireAt = "expire_at"
	// FieldServiceIds holds the string denoting the service_ids field in the database.
	FieldServiceIds = "service_ids"
	// FieldCouponType holds the string denoting the coupon_type field in the database.
	FieldCouponType = "coupon_type"
	// FieldMilestoneType holds the string denoting the milestone_type field in the database.
	FieldMilestoneType = "milestone_type"
	// FieldCurrencyID holds the string denoting the currency_id field in the database.
	FieldCurrencyID = "currency_id"
	// FieldUsageLimit holds the string denoting the usage_limit field in the database.
	FieldUsageLimit = "usage_limit"
	// FieldThreshold holds the string denoting the threshold field in the database.
	FieldThreshold = "threshold"
	// FieldStep holds the string denoting the step field in the database.
	FieldStep = "step"
	// FieldCouponValue holds the string denoting the coupon_value field in the database.
	FieldCouponValue = "coupon_value"
	// EdgeCurrency holds the string denoting the currency edge name in mutations.
	EdgeCurrency = "currency"
	// Table holds the table name of the milestone in the database.
	Table = "milestones"
	// CurrencyTable is the table that holds the currency relation/edge.
	CurrencyTable = "milestones"
	// CurrencyInverseTable is the table name for the Currency entity.
	// It exists in this package in order to avoid circular dependency with the "currency" package.
	CurrencyInverseTable = "currencies"
	// CurrencyColumn is the table column denoting the currency relation/edge.
	CurrencyColumn = "currency_id"
)

// Columns holds all SQL columns for milestone fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldStoreID,
	FieldExpireAt,
	FieldServiceIds,
	FieldCouponType,
	FieldMilestoneType,
	FieldCurrencyID,
	FieldUsageLimit,
	FieldThreshold,
	FieldStep,
	FieldCouponValue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// StoreIDValidator is a validator for the "store_id" field. It is called by the builders before save.
	StoreIDValidator func(string) error
	// DefaultServiceIds holds the default value on creation for the "service_ids" field.
	DefaultServiceIds []string
	// DefaultUsageLimit holds the default value on creation for the "usage_limit" field.
	DefaultUsageLimit int32
	// DefaultThreshold holds the default value on creation for the "threshold" field.
	DefaultThreshold int32
	// DefaultStep holds the default value on creation for the "step" field.
	DefaultStep int32
	// DefaultCouponValue holds the default value on creation for the "coupon_value" field.
	DefaultCouponValue float64
)

// OrderOption defines the ordering options for the Milestone queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStoreID orders the results by the store_id field.
func ByStoreID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoreID, opts...).ToFunc()
}

// ByExpireAt orders the results by the expire_at field.
func ByExpireAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpireAt, opts...).ToFunc()
}

// ByCouponType orders the results by the coupon_type field.
func ByCouponType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCouponType, opts...).ToFunc()
}

// ByMilestoneType orders the results by the milestone_type field.
func ByMilestoneType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMilestoneType, opts...).ToFunc()
}

// ByCurrencyID orders the results by the currency_id field.
func ByCurrencyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrencyID, opts...).ToFunc()
}

// ByUsageLimit orders the results by the usage_limit field.
func ByUsageLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLimit, opts...).ToFunc()
}

// ByThreshold orders the results by the threshold field.
func ByThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThreshold, opts...).ToFunc()
}

// ByStep orders the results by the step field.
func ByStep(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStep, opts...).ToFunc()
}

// ByCouponValue orders the results by the coupon_value field.
func ByCouponValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCouponValue, opts...).ToFunc()
}

// ByCurrencyField orders the results by currency field.
func ByCurrencyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCurrencyStep(), sql.OrderByField(field, opts...))
	}
}
func newCurrencyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CurrencyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CurrencyTable, CurrencyColumn),
	)
}
