// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	entcoupon "github.com/chisdev/coupon/pkg/ent/coupon"
	"github.com/chisdev/coupon/pkg/ent/couponbooking"
	"github.com/chisdev/coupon/pkg/ent/currency"
	"github.com/chisdev/coupon/pkg/ent/milestone"
	"github.com/chisdev/coupon/pkg/ent/progress"
	"github.com/chisdev/coupon/pkg/ent/reward"
	"github.com/chisdev/coupon/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	entcouponMixin := schema.Coupon{}.Mixin()
	entcouponMixinFields0 := entcouponMixin[0].Fields()
	_ = entcouponMixinFields0
	entcouponFields := schema.Coupon{}.Fields()
	_ = entcouponFields
	// entcouponDescCreatedAt is the schema descriptor for created_at field.
	entcouponDescCreatedAt := entcouponMixinFields0[1].Descriptor()
	// entcoupon.DefaultCreatedAt holds the default value on creation for the created_at field.
	entcoupon.DefaultCreatedAt = entcouponDescCreatedAt.Default.(func() time.Time)
	// entcouponDescUpdatedAt is the schema descriptor for updated_at field.
	entcouponDescUpdatedAt := entcouponMixinFields0[2].Descriptor()
	// entcoupon.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	entcoupon.DefaultUpdatedAt = entcouponDescUpdatedAt.Default.(func() time.Time)
	// entcoupon.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	entcoupon.UpdateDefaultUpdatedAt = entcouponDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entcouponDescValue is the schema descriptor for value field.
	entcouponDescValue := entcouponFields[1].Descriptor()
	// entcoupon.DefaultValue holds the default value on creation for the value field.
	entcoupon.DefaultValue = entcouponDescValue.Default.(float64)
	// entcouponDescStoreID is the schema descriptor for store_id field.
	entcouponDescStoreID := entcouponFields[2].Descriptor()
	// entcoupon.StoreIDValidator is a validator for the "store_id" field. It is called by the builders before save.
	entcoupon.StoreIDValidator = entcouponDescStoreID.Validators[0].(func(string) error)
	// entcouponDescServiceIds is the schema descriptor for service_ids field.
	entcouponDescServiceIds := entcouponFields[5].Descriptor()
	// entcoupon.DefaultServiceIds holds the default value on creation for the service_ids field.
	entcoupon.DefaultServiceIds = entcouponDescServiceIds.Default.([]uint64)
	// entcouponDescUsageLimit is the schema descriptor for usage_limit field.
	entcouponDescUsageLimit := entcouponFields[8].Descriptor()
	// entcoupon.DefaultUsageLimit holds the default value on creation for the usage_limit field.
	entcoupon.DefaultUsageLimit = entcouponDescUsageLimit.Default.(int32)
	couponbookingMixin := schema.CouponBooking{}.Mixin()
	couponbookingMixinFields0 := couponbookingMixin[0].Fields()
	_ = couponbookingMixinFields0
	couponbookingFields := schema.CouponBooking{}.Fields()
	_ = couponbookingFields
	// couponbookingDescCreatedAt is the schema descriptor for created_at field.
	couponbookingDescCreatedAt := couponbookingMixinFields0[1].Descriptor()
	// couponbooking.DefaultCreatedAt holds the default value on creation for the created_at field.
	couponbooking.DefaultCreatedAt = couponbookingDescCreatedAt.Default.(func() time.Time)
	// couponbookingDescUpdatedAt is the schema descriptor for updated_at field.
	couponbookingDescUpdatedAt := couponbookingMixinFields0[2].Descriptor()
	// couponbooking.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	couponbooking.DefaultUpdatedAt = couponbookingDescUpdatedAt.Default.(func() time.Time)
	// couponbooking.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	couponbooking.UpdateDefaultUpdatedAt = couponbookingDescUpdatedAt.UpdateDefault.(func() time.Time)
	currencyMixin := schema.Currency{}.Mixin()
	currencyMixinFields0 := currencyMixin[0].Fields()
	_ = currencyMixinFields0
	currencyFields := schema.Currency{}.Fields()
	_ = currencyFields
	// currencyDescCreatedAt is the schema descriptor for created_at field.
	currencyDescCreatedAt := currencyMixinFields0[1].Descriptor()
	// currency.DefaultCreatedAt holds the default value on creation for the created_at field.
	currency.DefaultCreatedAt = currencyDescCreatedAt.Default.(func() time.Time)
	// currencyDescUpdatedAt is the schema descriptor for updated_at field.
	currencyDescUpdatedAt := currencyMixinFields0[2].Descriptor()
	// currency.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	currency.DefaultUpdatedAt = currencyDescUpdatedAt.Default.(func() time.Time)
	// currency.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	currency.UpdateDefaultUpdatedAt = currencyDescUpdatedAt.UpdateDefault.(func() time.Time)
	milestoneMixin := schema.Milestone{}.Mixin()
	milestoneMixinFields0 := milestoneMixin[0].Fields()
	_ = milestoneMixinFields0
	milestoneFields := schema.Milestone{}.Fields()
	_ = milestoneFields
	// milestoneDescCreatedAt is the schema descriptor for created_at field.
	milestoneDescCreatedAt := milestoneMixinFields0[1].Descriptor()
	// milestone.DefaultCreatedAt holds the default value on creation for the created_at field.
	milestone.DefaultCreatedAt = milestoneDescCreatedAt.Default.(func() time.Time)
	// milestoneDescUpdatedAt is the schema descriptor for updated_at field.
	milestoneDescUpdatedAt := milestoneMixinFields0[2].Descriptor()
	// milestone.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	milestone.DefaultUpdatedAt = milestoneDescUpdatedAt.Default.(func() time.Time)
	// milestone.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	milestone.UpdateDefaultUpdatedAt = milestoneDescUpdatedAt.UpdateDefault.(func() time.Time)
	// milestoneDescName is the schema descriptor for name field.
	milestoneDescName := milestoneFields[0].Descriptor()
	// milestone.NameValidator is a validator for the "name" field. It is called by the builders before save.
	milestone.NameValidator = milestoneDescName.Validators[0].(func(string) error)
	// milestoneDescStoreID is the schema descriptor for store_id field.
	milestoneDescStoreID := milestoneFields[1].Descriptor()
	// milestone.StoreIDValidator is a validator for the "store_id" field. It is called by the builders before save.
	milestone.StoreIDValidator = milestoneDescStoreID.Validators[0].(func(string) error)
	progressMixin := schema.Progress{}.Mixin()
	progressMixinFields0 := progressMixin[0].Fields()
	_ = progressMixinFields0
	progressFields := schema.Progress{}.Fields()
	_ = progressFields
	// progressDescCreatedAt is the schema descriptor for created_at field.
	progressDescCreatedAt := progressMixinFields0[1].Descriptor()
	// progress.DefaultCreatedAt holds the default value on creation for the created_at field.
	progress.DefaultCreatedAt = progressDescCreatedAt.Default.(func() time.Time)
	// progressDescUpdatedAt is the schema descriptor for updated_at field.
	progressDescUpdatedAt := progressMixinFields0[2].Descriptor()
	// progress.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	progress.DefaultUpdatedAt = progressDescUpdatedAt.Default.(func() time.Time)
	// progress.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	progress.UpdateDefaultUpdatedAt = progressDescUpdatedAt.UpdateDefault.(func() time.Time)
	// progressDescCustomerID is the schema descriptor for customer_id field.
	progressDescCustomerID := progressFields[0].Descriptor()
	// progress.CustomerIDValidator is a validator for the "customer_id" field. It is called by the builders before save.
	progress.CustomerIDValidator = progressDescCustomerID.Validators[0].(func(string) error)
	// progressDescProgress is the schema descriptor for progress field.
	progressDescProgress := progressFields[2].Descriptor()
	// progress.DefaultProgress holds the default value on creation for the progress field.
	progress.DefaultProgress = progressDescProgress.Default.(int32)
	// progressDescPassCount is the schema descriptor for pass_count field.
	progressDescPassCount := progressFields[3].Descriptor()
	// progress.DefaultPassCount holds the default value on creation for the pass_count field.
	progress.DefaultPassCount = progressDescPassCount.Default.(int32)
	rewardMixin := schema.Reward{}.Mixin()
	rewardMixinFields0 := rewardMixin[0].Fields()
	_ = rewardMixinFields0
	rewardFields := schema.Reward{}.Fields()
	_ = rewardFields
	// rewardDescCreatedAt is the schema descriptor for created_at field.
	rewardDescCreatedAt := rewardMixinFields0[1].Descriptor()
	// reward.DefaultCreatedAt holds the default value on creation for the created_at field.
	reward.DefaultCreatedAt = rewardDescCreatedAt.Default.(func() time.Time)
	// rewardDescUpdatedAt is the schema descriptor for updated_at field.
	rewardDescUpdatedAt := rewardMixinFields0[2].Descriptor()
	// reward.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	reward.DefaultUpdatedAt = rewardDescUpdatedAt.Default.(func() time.Time)
	// reward.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	reward.UpdateDefaultUpdatedAt = rewardDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rewardDescServiceIds is the schema descriptor for service_ids field.
	rewardDescServiceIds := rewardFields[2].Descriptor()
	// reward.DefaultServiceIds holds the default value on creation for the service_ids field.
	reward.DefaultServiceIds = rewardDescServiceIds.Default.([]uint64)
	// rewardDescUsageLimit is the schema descriptor for usage_limit field.
	rewardDescUsageLimit := rewardFields[5].Descriptor()
	// reward.DefaultUsageLimit holds the default value on creation for the usage_limit field.
	reward.DefaultUsageLimit = rewardDescUsageLimit.Default.(int32)
	// rewardDescCouponValue is the schema descriptor for coupon_value field.
	rewardDescCouponValue := rewardFields[6].Descriptor()
	// reward.DefaultCouponValue holds the default value on creation for the coupon_value field.
	reward.DefaultCouponValue = rewardDescCouponValue.Default.(float64)
}
