// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	entcoupon "github.com/chisdev/coupon/pkg/ent/coupon"
	"github.com/chisdev/coupon/pkg/ent/currency"
	"github.com/chisdev/coupon/pkg/ent/milestone"
	"github.com/chisdev/coupon/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	entcouponMixin := schema.Coupon{}.Mixin()
	entcouponMixinFields0 := entcouponMixin[0].Fields()
	_ = entcouponMixinFields0
	entcouponFields := schema.Coupon{}.Fields()
	_ = entcouponFields
	// entcouponDescCreatedAt is the schema descriptor for created_at field.
	entcouponDescCreatedAt := entcouponMixinFields0[1].Descriptor()
	// entcoupon.DefaultCreatedAt holds the default value on creation for the created_at field.
	entcoupon.DefaultCreatedAt = entcouponDescCreatedAt.Default.(func() time.Time)
	// entcouponDescUpdatedAt is the schema descriptor for updated_at field.
	entcouponDescUpdatedAt := entcouponMixinFields0[2].Descriptor()
	// entcoupon.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	entcoupon.DefaultUpdatedAt = entcouponDescUpdatedAt.Default.(func() time.Time)
	// entcoupon.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	entcoupon.UpdateDefaultUpdatedAt = entcouponDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entcouponDescValue is the schema descriptor for value field.
	entcouponDescValue := entcouponFields[1].Descriptor()
	// entcoupon.DefaultValue holds the default value on creation for the value field.
	entcoupon.DefaultValue = entcouponDescValue.Default.(float64)
	// entcouponDescStoreID is the schema descriptor for store_id field.
	entcouponDescStoreID := entcouponFields[2].Descriptor()
	// entcoupon.StoreIDValidator is a validator for the "store_id" field. It is called by the builders before save.
	entcoupon.StoreIDValidator = entcouponDescStoreID.Validators[0].(func(string) error)
	// entcouponDescServiceIds is the schema descriptor for service_ids field.
	entcouponDescServiceIds := entcouponFields[5].Descriptor()
	// entcoupon.DefaultServiceIds holds the default value on creation for the service_ids field.
	entcoupon.DefaultServiceIds = entcouponDescServiceIds.Default.([]string)
	// entcouponDescUsageLimit is the schema descriptor for usage_limit field.
	entcouponDescUsageLimit := entcouponFields[8].Descriptor()
	// entcoupon.DefaultUsageLimit holds the default value on creation for the usage_limit field.
	entcoupon.DefaultUsageLimit = entcouponDescUsageLimit.Default.(int32)
	// entcouponDescUsedCount is the schema descriptor for used_count field.
	entcouponDescUsedCount := entcouponFields[9].Descriptor()
	// entcoupon.DefaultUsedCount holds the default value on creation for the used_count field.
	entcoupon.DefaultUsedCount = entcouponDescUsedCount.Default.(int32)
	// entcouponDescReservedCount is the schema descriptor for reserved_count field.
	entcouponDescReservedCount := entcouponFields[11].Descriptor()
	// entcoupon.DefaultReservedCount holds the default value on creation for the reserved_count field.
	entcoupon.DefaultReservedCount = entcouponDescReservedCount.Default.(int32)
	currencyMixin := schema.Currency{}.Mixin()
	currencyMixinFields0 := currencyMixin[0].Fields()
	_ = currencyMixinFields0
	currencyFields := schema.Currency{}.Fields()
	_ = currencyFields
	// currencyDescCreatedAt is the schema descriptor for created_at field.
	currencyDescCreatedAt := currencyMixinFields0[1].Descriptor()
	// currency.DefaultCreatedAt holds the default value on creation for the created_at field.
	currency.DefaultCreatedAt = currencyDescCreatedAt.Default.(func() time.Time)
	// currencyDescUpdatedAt is the schema descriptor for updated_at field.
	currencyDescUpdatedAt := currencyMixinFields0[2].Descriptor()
	// currency.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	currency.DefaultUpdatedAt = currencyDescUpdatedAt.Default.(func() time.Time)
	// currency.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	currency.UpdateDefaultUpdatedAt = currencyDescUpdatedAt.UpdateDefault.(func() time.Time)
	milestoneMixin := schema.Milestone{}.Mixin()
	milestoneMixinFields0 := milestoneMixin[0].Fields()
	_ = milestoneMixinFields0
	milestoneFields := schema.Milestone{}.Fields()
	_ = milestoneFields
	// milestoneDescCreatedAt is the schema descriptor for created_at field.
	milestoneDescCreatedAt := milestoneMixinFields0[1].Descriptor()
	// milestone.DefaultCreatedAt holds the default value on creation for the created_at field.
	milestone.DefaultCreatedAt = milestoneDescCreatedAt.Default.(func() time.Time)
	// milestoneDescUpdatedAt is the schema descriptor for updated_at field.
	milestoneDescUpdatedAt := milestoneMixinFields0[2].Descriptor()
	// milestone.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	milestone.DefaultUpdatedAt = milestoneDescUpdatedAt.Default.(func() time.Time)
	// milestone.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	milestone.UpdateDefaultUpdatedAt = milestoneDescUpdatedAt.UpdateDefault.(func() time.Time)
	// milestoneDescStoreID is the schema descriptor for store_id field.
	milestoneDescStoreID := milestoneFields[1].Descriptor()
	// milestone.StoreIDValidator is a validator for the "store_id" field. It is called by the builders before save.
	milestone.StoreIDValidator = milestoneDescStoreID.Validators[0].(func(string) error)
	// milestoneDescServiceIds is the schema descriptor for service_ids field.
	milestoneDescServiceIds := milestoneFields[3].Descriptor()
	// milestone.DefaultServiceIds holds the default value on creation for the service_ids field.
	milestone.DefaultServiceIds = milestoneDescServiceIds.Default.([]string)
	// milestoneDescUsageLimit is the schema descriptor for usage_limit field.
	milestoneDescUsageLimit := milestoneFields[7].Descriptor()
	// milestone.DefaultUsageLimit holds the default value on creation for the usage_limit field.
	milestone.DefaultUsageLimit = milestoneDescUsageLimit.Default.(int32)
	// milestoneDescThreshold is the schema descriptor for threshold field.
	milestoneDescThreshold := milestoneFields[8].Descriptor()
	// milestone.DefaultThreshold holds the default value on creation for the threshold field.
	milestone.DefaultThreshold = milestoneDescThreshold.Default.(int32)
	// milestoneDescStep is the schema descriptor for step field.
	milestoneDescStep := milestoneFields[9].Descriptor()
	// milestone.DefaultStep holds the default value on creation for the step field.
	milestone.DefaultStep = milestoneDescStep.Default.(int32)
	// milestoneDescCouponValue is the schema descriptor for coupon_value field.
	milestoneDescCouponValue := milestoneFields[10].Descriptor()
	// milestone.DefaultCouponValue holds the default value on creation for the coupon_value field.
	milestone.DefaultCouponValue = milestoneDescCouponValue.Default.(float64)
}
