// Code generated by mykit. DO NOT EDIT.
// Version v1.0.6

package client

import (
	"github.com/ChisTrun/carbon/api"
	client "github.com/ChisTrun/grpc/pkg/client"
	"google.golang.org/grpc"

	pb "github.com/chisdev/coupon/api"
)

type CouponCmsClient struct {
	pb.CouponCmsClient
}

func NewCouponCmsClient(config *carbon.TCPSocket, options ...grpc.DialOption) (*CouponCmsClient, error) {
	conn, err := client.NewClientConnection(config, options...)
	if err != nil {
		return nil, err
	}
	return &CouponCmsClient{
		CouponCmsClient: pb.NewCouponCmsClient(conn),
	}, nil
}
