// Code generated by mykit. DO NOT EDIT.
// Version v1.0.6

package client

import (
	"github.com/ChisTrun/carbon/api"
	client "github.com/ChisTrun/grpc/pkg/client"
	"google.golang.org/grpc"

	pb "github.com/chisdev/coupon/api"
)

type CouponClient struct {
	pb.CouponClient
}

func NewCouponClient(config *carbon.TCPSocket, options ...grpc.DialOption) (*CouponClient, error) {
	conn, err := client.NewClientConnection(config, options...)
	if err != nil {
		return nil, err
	}
	return &CouponClient{
		CouponClient: pb.NewCouponClient(conn),
	}, nil
}
